#!/bin/bash
if [ ! -e menu ]; then
    wget http://www2.ucar.edu/for-staff/daily/menu &>/dev/null
    grep -e "views-field" -e Pizza -e Sandwich -e Entr -e Chef -e Soup -e Grill menu \
        | sed -e 's/<[^>]*>//g;s/&[^;]*;//g; s/          //g'
    rm menu
else
    echo 'menu file already exists!'
fi;
